version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  # vue: # name of the first service
  #   build: frontend # specify the directory of the Dockerfile
  #   ports:
  #     - "4200:4200" # specify port forwarding

  express: #name of the second service
    build: backend # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forwarding
    depends_on: 
      - mongo
    environment:
      - DATABASE_URL=mongo

  mongo: # name of the third service
    image: mongo # specify image to build container from
    volumes: 
      - ./db:/data/db # map current db directory to container dir
    ports:
      - "27017:27017" # specify port forwarding
    env_file: 
      - ./backend/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      # MONGO_INITDB_DATABASE: project

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: 
      - ./backend/.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    depends_on: 
      - mongo

  # mongo-express:
  #   image: mongo-express
  #   env_file: 
  #     - ./backend/.env
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
  #     - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
  #     - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
  #     - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
  #     - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
  #     - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "8081:8081"